# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

# The macro below is expanded when 'realpath' is not built-in.
# Built-in 'realpath' is available on GNU Make 3.81.
realpath = $(shell cd $(1); pwd)

ROOT_SRCDIR    := $(call realpath, /uscms_data/d2/andersj/ROOT/root528/root)
ROOT_OBJDIR    := $(call realpath, /uscms_data/d2/andersj/ROOT/root528/root)

ifndef ROOT_SRCDIR
$(error Error determining ROOT_SRCDIR)
endif
ifndef ROOT_OBJDIR
$(error Error determining ROOT_OBJDIR)
endif

# The macro below strips off the source dir path to make a relative path name
stripsrc = $(subst $(ROOT_SRCDIR)/,,$(1))

ARCH           := linuxx8664gcc
HOST           := 

USECONFIG      := FALSE
MKLIBOPTIONS   := 

EXTRA_CFLAGS   := -Iinclude 
EXTRA_CXXFLAGS := -Iinclude 
EXTRA_LDFLAGS  := 
WINRTDEBUG     := no

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=  -DR__KRB5    -DR__SSL -DOPENSSL_NO_KRB5

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man/man1
DATADIR        := $(ROOTSYS)
ELISPDIR       := $(ROOTSYS)/build/misc
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := .
ICONPATH       := $(ROOTSYS)/icons
CINTINCDIR     := $(ROOTSYS)/cint
DOCDIR         := $(ROOTSYS)
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/build/misc

BUILDX11       := yes
X11LIBDIR      := 
XPMLIBDIR      := 
XPMLIB         := -lXpm
XFTLIB         := yes

EXCEPTIONS     := yes
EXPLICITLINK   := no

ENABLETHREAD   := yes
OSTHREADFLAG   := -pthread
OSTHREADLIBDIR := 
OSTHREADLIB    := -pthread

BUILTINFREETYPE:= no

BUILTINPCRE    := yes

BUILTINZLIB    := no
ZLIBLIBDIR     := 
ZLIBCLILIB     := -lz
ZLIBINCDIR     := $(filter-out /usr/include, /usr/include)

BUILDGL        := no
OPENGLLIBDIR   := 
OPENGLULIB     := 
OPENGLLIB      := -lGL
OPENGLINCDIR   := $(filter-out /usr/include, /usr/include)

BUILDLDAP      := yes
LDAPLIBDIR     :=   
LDAPCLILIB     :=  -lldap -llber
LDAPINCDIR     := $(filter-out /usr/include, /usr/include)

BUILDMYSQL     := no
MYSQLLIBDIR    := 
MYSQLCLILIB    := 
MYSQLINCDIR    := $(filter-out /usr/include, )

BUILDORACLE    := no
ORACLELIBDIR   := 
ORACLECLILIB   :=  
ORACLEINCDIR   := $(filter-out /usr/include, )

BUILDPGSQL     := no
PGSQLLIBDIR    := 
PGSQLCLILIB    := 
PGSQLINCDIR    := $(filter-out /usr/include, )

BUILDSAPDB     := no
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := no
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDQT        := no
BUILDQTGSI     := no
QTLIBDIR       := 
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, )
QTVERS	       := 
QTMOCEXE       := 

BUILDRFIO      := no
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := no
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, )
CASTORCFLAGS   := 

BUILDDCAP      := no
DCAPLIBDIR     := 
DCAPLIB        := 
DCAPINCDIR     := $(filter-out /usr/include, )

BUILDFTGL      := no
FTGLLIBDIR     := 
FTGLLIBS       := 
FTGLINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := no
GLEWLIBDIR     := 
GLEWLIBS       := 
GLEWINCDIR     := $(filter-out /usr/include, )
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := no
GFALLIBDIR     := 
GFALCLILIB     := 
GFALINCDIR     := $(filter-out /usr/include, )

BUILDGLITE     := no
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := yes

BUILDBONJOUR   := no
DNSSDLIBDIR    := 
DNSSDLIB       := 
DNSSDINCDIR    := $(filter-out /usr/include, )
BONJOURCPPFLAGS := 

BUILDCHIRP     := no
CHIRPLIBDIR    := 
CHIRPCLILIB    := 
CHIRPINCDIR    := $(filter-out /usr/include, )

BUILDHDFS      := no
HDFSLIBDIR     := 
HDFSCLILIB     := 
HDFSINCDIR     := $(filter-out /usr/include, )
JNIINCDIR      := $(filter-out /usr/include, ) $(filter-out /usr/include, /linux)
JVMCLILIB      := 
JVMLIBDIR      := 

BUILDALIEN     := no
ALIENLIBDIR    := 
ALIENCLILIB    := 
ALIENINCDIR    := $(filter-out /usr/include, )

BUILDASIMAGE   := yes
BUILTINASIMAGE := yes
ASEXTRALIB     :=  -ljpeg -ltiff -lungif -lpng -lz
ASEXTRALIBDIR  :=      
ASJPEGINCDIR   := $(filter-out /usr/include, /usr/include)
ASPNGINCDIR    := $(filter-out /usr/include, /usr/include)
ASTIFFINCDIR   := $(filter-out /usr/include, /usr/include)
ASGIFINCDIR    := $(filter-out /usr/include, /usr/include)
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := no
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := 
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := no
FPYTHIA8INCDIR   := 
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := 

BUILDFFTW3     := yes
FFTW3LIBDIR    := 
FFTW3LIB       := /uscmst1/prod/sw/cms/slc5_amd64_gcc434/external/fftw3/3.2.2-cms4/lib/libfftw3.a
FFTW3INCDIR    := $(filter-out /usr/include, /uscmst1/prod/sw/cms/slc5_amd64_gcc434/external/fftw3/3.2.2-cms4/include)

BUILDFITSIO    := no
CFITSIOLIBDIR  := 
CFITSIOLIB     := 
CFITSIOINCDIR  := $(filter-out /usr/include, )

BUILDGVIZ      := no
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := yes
PYTHONLIBDIR   := -L/uscmst1/prod/sw/cms/slc5_amd64_gcc434/external/python/2.6.4-cms14/lib
PYTHONLIB      := -lpython2.6
PYTHONINCDIR   := $(filter-out /usr/include, /uscmst1/prod/sw/cms/slc5_amd64_gcc434/external/python/2.6.4-cms14/include/python2.6)
PYTHONLIBFLAGS := 

BUILDRUBY      := no
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := yes
XMLLIBDIR      := 
XMLCLILIB      := -lxml2 -lz -lm
XMLINCDIR      := $(filter-out /usr/include, /usr/include/libxml2)

HASXRD         := yes
BUILDXRD       := yes
XRDINCDIR      := 
XRDLIBDIR      := 
XRDADDOPTS     := 
EXTRA_XRDFLAGS := -DUSENEWHDRS
XRDVERSION     := 300000002

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

ALLOCLIB       := 
ALLOCLIBDIR    := 

BUILDKRB5      := yes
KRB5LIB        := -lkrb5 -lk5crypto
KRB5LIBDIR     :=  
KRB5INCDIR     := $(filter-out /usr/include, /usr/include)
KRB5INIT       := /usr/kerberos/bin/kinit

COMERRLIB      := -lcom_err
COMERRLIBDIR   := 

RESOLVLIB      := -lresolv

CRYPTOLIB      := -lcrypto
CRYPTOLIBDIR   := 

BUILDGLOBUS    := no
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )
BUILDXRDGSI    := yes

BUILDMONALISA  := no
MONALISALIBDIR := 
MONALISACLILIB := 
MONALISAINCDIR := $(filter-out /usr/include, )

SSLLIB         := -lssl -lcrypto
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, /usr/include)
SSLSHARED      := yes

SHADOWFLAGS    := -DR__SHADOWPW 
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDGENVECTOR := yes

BUILDMATHMORE  := no
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := 
GSLVERSION     := 

BUILDCLING     := no

BUILDCINTEX    := yes

BUILDREFLEX    := yes

BUILDROOFIT    := yes

BUILDMINUIT2   := 

BUILDUNURAN    := 

BUILDGDML      := 

BUILDTABLE     := 

BUILDTMVA      := yes

BUILDCLARENS   := no
CLARENSINC     := $(filter-out -I/usr/include, )
CLARENSLIBS    := 

BUILDPEAC      := no

BUILDAFDSMGRD  := no
AFDSMGRDAPMON  := 

CURSESINCDIR   := $(filter-out -I/usr/include, -I/usr/include/ncurses)
CURSESLIBDIR   := 
CURSESHDR      := ncurses.h
CURSESLIB      := -lncurses
BUILDEDITLINE  := yes

CPPUNIT        := 
GCCXML         := 

ROOTDICTTYPE   := cint

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p
RSYNC          := rsync -au

ROOTDRPMREL    := 1
