/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux lpcdt063.fnal.gov 2.6.18-238.19.1.el5 #1 SMP Fri Jul 15 00:48:58 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux" 
#define COMPILER "/uscmst1/prod/sw/cms/slc5_amd64_gcc434/external/gcc/4.3.4-cms/bin/g++" 
#define COMPILERVERS "gcc434"
#define MAKESHAREDLIB  "cd $BuildDir ; g++ -c $Opt -pipe -m64 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles ; g++ $ObjectFiles -shared -Wl,-soname,$LibName.so -m64 -O2  $DepLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; g++ -c  -pipe -m64 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles; g++ $ObjectFiles -m64 -O2  -o $ExeName $LinkedLibs -lm -ldl  -pthread   -rdynamic"
#define CXXOPT "-O2"
#define CXXDEBUG "-g"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lCint -lMathCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o" 
#define SOEXT "so" 
