/********************************************************************
* net/krb5auth/src/G__Krb5Auth.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error net/krb5auth/src/G__Krb5Auth.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Krb5Auth();
extern void G__cpp_setup_inheritanceG__Krb5Auth();
extern void G__cpp_setup_typetableG__Krb5Auth();
extern void G__cpp_setup_memvarG__Krb5Auth();
extern void G__cpp_setup_globalG__Krb5Auth();
extern void G__cpp_setup_memfuncG__Krb5Auth();
extern void G__cpp_setup_funcG__Krb5Auth();
extern void G__set_cpp_environmentG__Krb5Auth();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TKSocket.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__Krb5AuthLN_TClass;
extern G__linked_taginfo G__G__Krb5AuthLN_TBuffer;
extern G__linked_taginfo G__G__Krb5AuthLN_TMemberInspector;
extern G__linked_taginfo G__G__Krb5AuthLN_TObject;
extern G__linked_taginfo G__G__Krb5AuthLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__Krb5AuthLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Krb5AuthLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__Krb5AuthLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__Krb5AuthLN_TSocket;
extern G__linked_taginfo G__G__Krb5AuthLN_TKSocket;
extern G__linked_taginfo G__G__Krb5AuthLN_TKSocketcLcLEEncoding;

/* STUB derived class for protected member access */
